Repository kruzhok-team/lapki-client, pull requests merged in 2023-10, with the labels that each got.

#38 fix open file function, fix components update after new file open
  src/renderer/src/components/Menu.tsx
  src/renderer/src/lib/data/EditorManager.ts
Labels: hacktoberfest-accepted

#40 Пачка фиксов
  .eslintrc.json
  .prettierrc
  src/main/index.ts
  src/renderer/src/lib/data/PlatformManager.tsx
  src/renderer/src/lib/drawable/Picto.tsx
Labels: hacktoberfest-accepted

#20 Undo redo
  .eslintrc.json
  src/renderer/src/assets/icons/arrow-down.svg
  src/renderer/src/assets/icons/history.svg
  src/renderer/src/components/ComponentEditModal.tsx
  src/renderer/src/components/DiagramEditor.tsx
  src/renderer/src/components/Sidebar/Compiler.tsx
  src/renderer/src/components/Sidebar/Explorer.tsx
  src/renderer/src/components/Sidebar/History.tsx
  src/renderer/src/components/Sidebar/Loader.tsx
  src/renderer/src/components/Sidebar/Menu.tsx
  src/renderer/src/components/Sidebar/Menus.tsx
  src/renderer/src/components/Sidebar/Setting.tsx
  src/renderer/src/components/Sidebar/Sidebar.tsx
  src/renderer/src/components/index.ts
  src/renderer/src/hooks/useAddComponent.ts
  src/renderer/src/hooks/useDiagramContextMenu.ts
  src/renderer/src/hooks/useEditDeleteComponent.ts
  src/renderer/src/lib/Component.tsx
  src/renderer/src/lib/basic/Container.ts
  src/renderer/src/lib/basic/Keyboard.ts
  src/renderer/src/lib/common/EventEmitter.ts
  src/renderer/src/lib/data/EditorManager.ts
  src/renderer/src/lib/data/StateMachine.ts
  src/renderer/src/lib/data/UndoRedo.ts
  src/renderer/src/lib/drawable/Draggable.ts
  src/renderer/src/lib/drawable/States.ts
  src/renderer/src/lib/drawable/Transition.ts
  src/renderer/src/lib/drawable/Transitions.ts
  src/renderer/src/types/EditorManager.ts
  src/renderer/src/types/StateMachine.ts
  src/renderer/src/types/diagram.ts
  src/renderer/src/utils/index.ts
Labels: hacktoberfest-accepted

#42 Скругление углов
  src/renderer/src/lib/drawable/BaseTransition.ts
  src/renderer/src/lib/drawable/Condition.ts
  src/renderer/src/lib/drawable/Picto.tsx
  src/renderer/src/lib/utils.ts
Labels: hacktoberfest-accepted

#44 Центрирования камеры после открытия схемы
  src/renderer/src/lib/data/StateMachine.ts
Labels: hacktoberfest-accepted

#48 Редизайн клиента.
  src/renderer/src/assets/icons/arrow_down_right.svg
  src/renderer/src/assets/icons/center_focus_2.svg
  src/renderer/src/assets/icons/code.svg
  src/renderer/src/assets/icons/code_all_2.svg
  src/renderer/src/assets/icons/copy.svg
  src/renderer/src/assets/icons/delete.svg
  src/renderer/src/assets/icons/edit.svg
  src/renderer/src/assets/icons/event_add.svg
  src/renderer/src/assets/icons/icon.svg
  src/renderer/src/assets/icons/maximize.svg
  src/renderer/src/assets/icons/minimize.svg
  src/renderer/src/assets/icons/paste.svg
  src/renderer/src/assets/icons/state_add.svg
  src/renderer/src/components/DiagramContextMenu.tsx
  src/renderer/src/components/MainContainer.tsx
  src/renderer/src/components/Sidebar/History.tsx
  src/renderer/src/components/Sidebar/Menu.tsx
  src/renderer/src/components/Tabs/Tab.tsx
  src/renderer/src/hooks/useDiagramContextMenu.ts
  src/renderer/src/lib/basic/Container.ts
  src/renderer/src/lib/basic/Keyboard.ts
  src/renderer/src/lib/data/PlatformLoader.ts
Labels: hacktoberfest-accepted

#52 Initial node
  src/renderer/src/lib/basic/Keyboard.ts
  src/renderer/src/lib/data/StateMachine.ts
  src/renderer/src/lib/drawable/BaseTransition.ts
  src/renderer/src/lib/drawable/Condition.ts
  src/renderer/src/lib/drawable/GhostTransition.ts
  src/renderer/src/lib/drawable/InitialStateMark.ts
  src/renderer/src/lib/drawable/State.ts
  src/renderer/src/lib/drawable/States.ts
  src/renderer/src/lib/drawable/Transition.ts
  src/renderer/src/lib/utils.ts
Labels: hacktoberfest-accepted

#56 1) Избавление от бага начального экрана;
  src/renderer/src/components/DiagramContextMenu.tsx
  src/renderer/src/components/Sidebar/Menus.tsx
Labels: hacktoberfest-accepted

#64 add debounce to canvas resize event
  package-lock.json
  package.json
  src/renderer/src/lib/basic/Canvas.ts
Labels: hacktoberfest-accepted

#62 Очередь рендера
  src/renderer/src/lib/basic/Container.ts
  src/renderer/src/lib/data/DrawList.ts
  src/renderer/src/lib/data/StateMachine.ts
  src/renderer/src/lib/drawable/States.ts
  src/renderer/src/lib/drawable/Transitions.ts
Labels: enhancement, test-me

#68 Render queue refactor
  src/renderer/src/components/CreateModal.tsx
  src/renderer/src/components/DiagramEditor.tsx
  src/renderer/src/components/EventsModal.tsx
  src/renderer/src/components/Modal/TextSelect.tsx
  src/renderer/src/components/Sidebar/Explorer.tsx
  src/renderer/src/components/Sidebar/History.tsx
  src/renderer/src/hooks/useAddComponent.ts
  src/renderer/src/hooks/useDiagramContextMenu.ts
  src/renderer/src/hooks/useDiagramStateName.ts
  src/renderer/src/hooks/useEditDeleteComponent.ts
  src/renderer/src/hooks/useEditorManager.ts
  src/renderer/src/lib/basic/Container.ts
  src/renderer/src/lib/data/MachineController.ts
  src/renderer/src/lib/data/StatesController.ts
  src/renderer/src/lib/data/TransitionsController.ts
  src/renderer/src/lib/data/UndoRedo.ts
  src/renderer/src/lib/drawable/Children.ts
  src/renderer/src/lib/drawable/Condition.ts
  src/renderer/src/lib/drawable/Events.ts
  src/renderer/src/lib/drawable/InitialStateMark.ts
  src/renderer/src/lib/drawable/Node.ts
  src/renderer/src/lib/drawable/State.ts
  src/renderer/src/lib/drawable/Transition.ts
  src/renderer/src/lib/drawable/Transitions.ts
  src/renderer/src/types/MachineController.ts
  src/renderer/src/utils/index.ts
  tsconfig.web.json
Labels: hacktoberfest-accepted

#70 fix, link and unlink transition with states
  src/renderer/src/lib/basic/Container.ts
  src/renderer/src/lib/data/MachineController.ts
  src/renderer/src/lib/drawable/Children.ts
Labels: bug
