Repository kruzhok-team/lapki-client, pull requests merged in 2023-11, with the labels that each got.

#81 Фикс: при удалении вложенного состояния удалялись переходы родителя
  src/renderer/src/lib/data/MachineController.ts
  src/renderer/src/lib/data/StatesController.ts
  src/renderer/src/lib/data/UndoRedo.ts
  src/renderer/src/lib/drawable/Children.ts
  src/renderer/src/types/MachineController.ts
Labels: bug

#49 try state nesting
  package-lock.json
  package.json
  src/renderer/src/components/DiagramEditor.tsx
  src/renderer/src/lib/basic/Container.ts
  src/renderer/src/lib/data/MachineController.ts
  src/renderer/src/lib/data/StatesController.ts
  src/renderer/src/lib/drawable/Children.ts
  src/renderer/src/lib/drawable/Node.ts
  src/renderer/src/lib/drawable/State.ts
  src/renderer/src/types/drawable.ts
Labels: hacktoberfest-accepted, test-me

#67 Встроенный импорт-экспорт в Cyberiada-GraphML
  demos/CyberiadaSchemas/CyberiadaFormat-Autoborder.graphml
  demos/CyberiadaSchemas/CyberiadaFormat-Blinker.graphml
  package-lock.json
  package.json
  src/main/file-handlers.ts
  src/renderer/src/App.tsx
  src/renderer/src/components/Modules/Compiler.ts
  src/renderer/src/components/Sidebar/Compiler.tsx
  src/renderer/src/components/Sidebar/Menu.tsx
  src/renderer/src/components/Sidebar/Sidebar.tsx
  src/renderer/src/hooks/useDiagramContextMenu.ts
  src/renderer/src/hooks/useErrorModal.tsx
  src/renderer/src/hooks/useFileOperations.ts
  src/renderer/src/lib/data/EditorManager.ts
  src/renderer/src/lib/data/GraphmlParser.ts
  src/renderer/src/lib/data/PlatformLoader.ts
  src/renderer/src/types/diagram.ts
Labels: enhancement, critical
